export const OPEN_LOGIN_FORM = 'OPEN_LOGIN_FORM';
export const CLOSE_LOGIN_FORM = 'CLOSE_LOGIN_FORM';
export const OPEN_REGISTRATION_FORM = 'OPEN_REGISTRATION_FORM';
export const CLOSE_REGISTRATION_FORM = 'CLOSE_REGISTRATION_FORM';
export const UPDATE_USER = 'UPDATE_USER';
export const OPEN_BUY_INSURANCE = 'OPEN_BUY_INSURANCE';
export const CLOSE_BUY_INSURANCE = 'CLOSE_BUY_INSURANCE';
export const TRANSACTION_HASH = 'TRANSACTION_HASH';